### ISSUE TITLE
Fix missing humble branch.

### ISSUE THREAD

**Issue by orensbruli** [open-rmf/nlohmann_json_schema_validator_vendor#14]
As reported here: https://github.com/open-rmf/rmf/discussions/275#discussioncomment-4619231
Humble does not exist upstream.
It should point to this commit https://github.com/open-rmf/nlohmann_json_schema_validator_vendor/commit/0381c59370d23cd08b138411aa38292a1fcf1677

It looks like it was my own mistake after merging the latest changes, sorry. 
https://github.com/open-rmf/nlohmann_json_schema_validator_vendor/pull/13#event-7986130602
This will not happen again :wink: :stuck_out_tongue_winking_eye: 

@marcoag @mxgrey could you create it? Thank you.

**Comment by Yadunund** [comment]
Thanks for highlighting the problem @orensbruli! I've created the branch at that commit and pushed.
